databases:
  - name: kahani-db
    databaseName: kahani
    user: kahani

services:
  - type: web
    name: kahani
    env: node
    plan: starter
    buildCommand: npm install && vite build --outDir dist/public --emptyOutDir && esbuild server/index.ts --bundle --platform=node --outfile=dist/index.js --external:@neondatabase/serverless --external:ws
    startCommand: npm run db:push && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kahani-db
          property: connectionString