services:
  - type: web
    name: kahani
    env: node
    plan: starter
    buildCommand: npm install && vite build --outDir dist/public --emptyOutDir && esbuild server/index.ts --bundle --platform=node --outfile=dist/index.js --external:@neondatabase/serverless --external:ws
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production